# Use this notebook for your 3 choices of APIs

In [1]:
import requests
import pandas as pd

In [ ]:
#coindesk
#It is useful for a project like creating a dashboard for my self to track prices and the market.

In [4]:
url = "https://api.coindesk.com/v1/bpi/currentprice.json"
response = requests.get(url)
data = response.json()
bpi_data = data['bpi']
df = pd.DataFrame.from_dict(bpi_data, orient='index')

df

    code   symbol         rate             description  rate_float
USD  USD    &#36;  36,969.6582    United States Dollar  36969.6582
GBP  GBP  &pound;  30,891.5507  British Pound Sterling  30891.5507
EUR  EUR   &euro;  36,013.8447                    Euro  36013.8447

In [11]:
#World time API
#In the same project I could keep a very close track of the time in any part of the world in order to have a complete dashboard to analyze the market
timezone = 'Europe/Berlin'  
url = f'http://worldtimeapi.org/api/timezone/{timezone}'
response = requests.get(url)
data = response.json()
time_df = pd.DataFrame([data])
time_df

,abbreviation,client_ip,datetime,day_of_week,day_of_year,dst,dst_from,dst_offset,dst_until,raw_offset,timezone,unixtime,utc_datetime,utc_offset,week_number
0,CET,192.145.39.222,2023-11-21T19:56:29.617737+01:00,2,325,False,None,0,None,3600,Europe/Berlin,1700592989,2023-11-21T18:56:29.617737+00:00,+01:00,47

In [13]:
#realmealDB recipe API
#I could use this API to build and application that helps me cook with the ingredients I have left on the fridge.

In [14]:
ingredient = 'chicken' 
url = f'https://www.themealdb.com/api/json/v1/1/filter.php?i={ingredient}'

response = requests.get(url)
data = response.json()

recipes = data['meals']
recipes_df = pd.DataFrame(recipes)

recipes_df[['strMeal', 'strMealThumb']]

,strMeal,strMealThumb
0,Brown Stew Chicken,https://www.themealdb.com/images/media/meals/s...
1,Chicken & mushroom Hotpot,https://www.themealdb.com/images/media/meals/u...
2,Chicken Alfredo Primavera,https://www.themealdb.com/images/media/meals/s...
3,Chicken Basquaise,https://www.themealdb.com/images/media/meals/w...
4,Chicken Congee,https://www.themealdb.com/images/media/meals/1...
5,Chicken Handi,https://www.themealdb.com/images/media/meals/w...
6,Kentucky Fried Chicken,https://www.themealdb.com/images/media/meals/x...
7,Kung Pao Chicken,https://www.themealdb.com/images/media/meals/1...
8,Pad See Ew,https://www.themealdb.com/images/media/meals/u...
9,Piri-piri chicken and slaw,https://www.themealdb.com/images/media/meals/h...
10,Thai Green Curry,https://www.themealdb.com/images/media/meals/s...

In [16]:
ingredient = 'beef' 
url = f'https://www.themealdb.com/api/json/v1/1/filter.php?i={ingredient}'

response = requests.get(url)
data = response.json()

recipes = data['meals']
recipes_df = pd.DataFrame(recipes)
recipes_df[['strMeal', 'strMealThumb']]

,strMeal,strMealThumb
0,Beef and Mustard Pie,https://www.themealdb.com/images/media/meals/s...
1,Beef and Oyster pie,https://www.themealdb.com/images/media/meals/w...
2,Beef Asado,https://www.themealdb.com/images/media/meals/p...
3,Beef Caldereta,https://www.themealdb.com/images/media/meals/4...
4,Beef Dumpling Stew,https://www.themealdb.com/images/media/meals/u...
5,Beef Lo Mein,https://www.themealdb.com/images/media/meals/1...
6,Beef Mechado,https://www.themealdb.com/images/media/meals/c...
7,Beef Rendang,https://www.themealdb.com/images/media/meals/b...
8,Beef Sunday Roast,https://www.themealdb.com/images/media/meals/s...
9,Bistek,https://www.themealdb.com/images/media/meals/4...
10,Bitterballen (Dutch meatballs),https://www.themealdb.com/images/media/meals/l...
11,Braised Beef Chilli,https://www.themealdb.com/images/media/meals/u...
12,Egyptian Fatteh,https://www.themealdb.com/images/media/meals/r...
13,Massaman Beef curry,https://www.themealdb.com/images/media/meals/t...
14,Moussaka,https://www.themealdb.com/images/media/meals/c...
15,Mulukhiyah,https://www.themealdb.com/images/media/meals/x...
16,Red Peas Soup,https://www.themealdb.com/images/media/meals/s...
17,Steak and Kidney Pie,https://www.themealdb.com/images/media/meals/q...
18,Szechuan Beef,https://www.themealdb.com/images/media/meals/1...
19,Traditional Croatian Goulash,https://www.themealdb.com/images/media/meals/n...